### PR TITLE
Ci benchmark storing

### PR DESCRIPTION
**Pull request by cshezi**

### CODE REVIEW

**Comment by cshezi** [comment]
⚠️ Newman Test Results ⚠️ Performance might have improved <br /><br />Current number of tests is 1 and previous was 1 <br /><br />Response stats<blockquote> <li>Current response average is 98ms and previous was 99ms <br /><li>Current response min is 98ms and previous was 99ms <br /><li>Current response max is 98ms and previous was 99ms <br /><li>Response standard deviation 0ms <br /><br /> Previous PR was merged by cshezi and Pull request number is #86 at 2024-01-15T09:52:38Z

**Comment by cshezi** [comment]
🧪 Newman Test Results <br /> ❌ Performance declined <br /><br />Current number of tests is 1 and previous was 1 <br /><br />Response stats<blockquote> <li>Current response average is 120ms and previous was 99ms <br /><li>Current response min is 120ms and previous was 99ms <br /><li>Current response max is 120ms and previous was 99ms <br /><li>Response standard deviation 0ms <br /><br /> Previous PR was merged by cshezi and Pull request number is #86 at 2024-01-15T09:52:38Z

**Comment by cshezi** [comment]
🧪 <b>Newman Test Results<b/> <br /> ❌ Performance declined <br /><br />Current number of tests is 1 and previous was 1 <br /><br />Response stats<blockquote> <li>Current response average is 103ms and previous was 98ms <br /><li>Current response min is 103ms and previous was 98ms <br /><li>Current response max is 103ms and previous was 98ms <br /><li>Response standard deviation 0ms <br /><br /> Previous PR was merged by cshezi and Pull request number is #86 at 2024-01-15T09:54:41Z

**Comment by cshezi** [comment]
🧪 <b>Newman Test Results<b/> <br /> ⚠️ Performance might have declined <br /><br />Current number of tests is 1 and previous was 1 <br /><br />Response stats<blockquote> <li>Current response average is 99ms and previous was 98ms <br /><li>Current response min is 99ms and previous was 98ms <br /><li>Current response max is 99ms and previous was 98ms <br /><li>Response standard deviation 0ms <br /><br /> Previous PR was merged by cshezi and Pull request number is #86 at 2024-01-15T09:54:41Z

**Comment by cshezi** [comment]
🧪 <b>Newman Test Results<b/> <br /> ⚠️ Performance might have declined <br /><br />Current number of tests is 1 and previous was 1 <br /><br />Response stats<blockquote> <li>Current response average is 102ms and previous was 98ms <br /><li>Current response min is 102ms and previous was 98ms <br /><li>Current response max is 102ms and previous was 98ms <br /><li>Response standard deviation 0ms <br /><br /> Previous PR was merged by cshezi and Pull request number is #86 at 2024-01-15T09:54:41Z

**Comment by cshezi** [comment]
🧪 <b>Newman Test Results<b/> <br /> ⚠️ Performance might have declined <br /><br />Current number of tests is 1 and previous was 1 <br /><br />Response stats<blockquote> <li>Current response average is 102ms and previous was 98ms <br /><li>Current response min is 102ms and previous was 98ms <br /><li>Current response max is 102ms and previous was 98ms <br /><li>Response standard deviation 0ms <br /><br /> Previous PR was merged by cshezi and Pull request number is #86 at 2024-01-15T09:54:41Z

**Review by rtkay123 — APPROVED** [review]

**Pull request merged**
