### PR TITLE
Remove Channel

### PR DESCRIPTION
**Pull request by rtkay123**
Tracks: https://github.com/frmscoe/channel-router-setup-processor/issues/124

### CODE REVIEW

**Review by Sandy-at-Tazama — COMMENTED** [review]
## Readme

1. Sequence diagram includes `channel`

2. Response for Pain001 JSON  includes reference to `channel`

3. Acceptance criteria `5.Rename the Channel-router-setup-processor repository to Event-director`
3.1. Repository not updated in readme -headings, text
3.2.  Readme: Code for clone repo and install dependencies - ref CRSP (I'm not sure if this was supposes to be renamed? @Justus-at-Tazama )

4. Acceptance Criteria `8. Update documentation as follows:` - I was expecting headings as specified. @Justus-at-Tazama

**Review by Sandy-at-Tazama — DISMISSED** [review]
I assume rename of `channel-router-setup-processor` in `package-lock.json` will be part of the later ticket to rename repo
CRSP - rename repo #135

**Comment by rtkay123** [comment]
> I assume rename of `channel-router-setup-processor` in `package-lock.json` will be part of the later ticket to rename repo CRSP - rename repo #135

Updated on 3b1d0376cd1881db48b30ef987b2e6b7738b94bb

**Review by Lenbkr — APPROVED** [review]

**Review by Justus-at-Tazama — APPROVED** [review]
image

**Review by Lenbkr — APPROVED** [review]

**Pull request merged**
